<?php

include_once('wc_config.php');

$mike = array();
$mike['name'] = 'Vinny Vincenzos';
$mike['A']['FRANCE'] = FRANCE;
$mike['B']['ENGLAND'] = ENGLAND;
$mike['C']['BELGIUM'] = BELGIUM;
$mike['D']['CROATIA'] = CROATIA;
$mike['E']['SWITZERLAND'] = SWITZ;
$mike['F']['USA'] = USA;
$mike['G']['SOUTH KOREA'] = KOREA;
$mike['H']['JAPAN'] = JAPAN;
$mike['I']['AUSTRALIA'] = AUSTRALIA;
$mike['J']['COSTA RICA'] = COSTA;
$mike['K']['KANE'] = KANE;
$mike['L']['BENZEMA'] = BENZEMA;
$mike['M']['LUKAKU'] = LUKAKU;
$mike['N']['RICHARLISON'] = RICHARLISON;
$mike['O']['STERLING'] = STERLING;
$mike['P']['DE BRUYNE'] = DEBRUYNE;
$mike['Q']['BALE'] = BALE;
$mike['R']['MODRIC'] = MODRIC;
$mike['S']['JIMENEZ'] = JIMENEZ;
$mike['T']['LARIN'] = LARIN;
define('MIKE', serialize($mike));

$mike2 = array();
$mike2['name'] = 'Vinny Bellisimos';
$mike2['A']['BRAZIL'] = BRAZIL;
$mike2['B']['HOLLAND'] = HOLLAND;
$mike2['C']['BELGIUM'] = BELGIUM;
$mike2['D']['URUGUAY'] = URUGUAY;
$mike2['E']['SWITZERLAND'] = SWITZ;
$mike2['F']['SENEGAL'] = SENEGAL;
$mike2['G']['KOREA'] = KOREA;
$mike2['H']['CANADA'] = CANADA;
$mike2['I']['CAMEROON'] = CAMEROON;
$mike2['J']['COSTA RICA'] = COSTA;
$mike2['K']['MBAPPE'] = MBAPPE;
$mike2['L']['NEYMAR'] = NEYMAR;
$mike2['M']['VINICIUS JR'] = VINI;
$mike2['N']['MORATA'] = MORATA;
$mike2['O']['STERLING'] = STERLING;
$mike2['P']['NUNEZ'] = NUNEZ;
$mike2['Q']['GAKPO'] = GAKPO;
$mike2['R']['MODRIC'] = MODRIC;
$mike2['S']['AYEW'] = AYEW;
$mike2['T']['LARIN'] = LARIN;
define('MIKE2', serialize($mike2));

$james = array();
$james['name'] = 'Baggio\'s Rat Tail';
$james['A']['BRAZIL'] = BRAZIL;
$james['B']['ENGLAND'] = ENGLAND;
$james['C']['GERMANY'] = GERMANY;
$james['D']['DENMARK'] = DENMARK;
$james['E']['SWITZERLAND'] = SWITZ;
$james['F']['USA'] = USA;
$james['G']['WALES'] = WALES;
$james['H']['JAPAN'] = JAPAN;
$james['I']['AUSTRALIA'] = AUSTRALIA;
$james['J']['TUNISIA'] = TUNISIA;
$james['K']['KANE'] = KANE;
$james['L']['NEYMAR'] = NEYMAR;
$james['M']['VINICIUS JR'] = VINI;
$james['N']['MORATA'] = MORATA;
$james['O']['GNABRY'] = GNABRY;
$james['P']['NUNEZ'] = NUNEZ;
$james['Q']['SANE'] = SANE;
$james['R']['PULISIC'] = PULISIC;
$james['S']['KAMADA'] = KAMADA;
$james['T']['DAVID'] = DAVID;
define('JAMES', serialize($james));

$james2 = array();
$james2['name'] = 'Joachim Low\'s Boogers';
$james2['A']['FRANCE'] = FRANCE;
$james2['B']['SPAIN'] = SPAIN;
$james2['C']['PORTUGAL'] = PORTUGAL;
$james2['D']['URUGUAY'] = URUGUAY;
$james2['E']['SWITZERLAND'] = SWITZ;
$james2['F']['USA'] = USA;
$james2['G']['WALES'] = WALES;
$james2['H']['CANADA'] = CANADA;
$james2['I']['AUSTRALIA'] = AUSTRALIA;
$james2['J']['TUNISIA'] = TUNISIA;
$james2['K']['MBAPPE'] = MBAPPE;
$james2['L']['RONALDO'] = RONALDO;
$james2['M']['DEPAY'] = DEPAY;
$james2['N']['MORATA'] = MORATA;
$james2['O']['TORRES'] = TORRES;
$james2['P']['NUNEZ'] = NUNEZ;
$james2['Q']['GAKPO'] = GAKPO;
$james2['R']['BERNARDO'] = BERNARDO;
$james2['S']['KAMADA'] = KAMADA;
$james2['T']['DAVID'] = DAVID;
define('JAMES2', serialize($james2));

$seb = array();
$seb['name'] = 'Sebnaldo';
$seb['A']['BRAZIL'] = BRAZIL;
$seb['B']['SPAIN'] = SPAIN;
$seb['C']['GERMANY'] = GERMANY;
$seb['D']['DENMARK'] = DENMARK;
$seb['E']['MEXICO'] = MEXICO;
$seb['F']['SENEGAL'] = SENEGAL;
$seb['G']['MOROCCO'] = MOROCCO;
$seb['H']['CANADA'] = CANADA;
$seb['I']['IRAN'] = IRAN;
$seb['J']['COSTA RICA'] = COSTA;
$seb['K']['MBAPPE'] = MBAPPE;
$seb['L']['NEYMAR'] = NEYMAR;
$seb['M']['VINICIUS JR'] = VINI;
$seb['N']['HAVERTZ'] = HAVERTZ;
$seb['O']['TORRES'] = TORRES;
$seb['P']['ANSU FATI'] = FATI;
$seb['Q']['SANE'] = SANE;
$seb['R']['BERNARDO'] = BERNARDO;
$seb['S']['JIMENEZ'] = JIMENEZ;
$seb['T']['DAVIES'] = DAVIES;
define('SEB', serialize($seb));

$dave = array();
$dave['name'] = 'The ghost of Maradona';
$dave['A']['ARGENTINA'] = ARGENTINA;
$dave['B']['HOLLAND'] = HOLLAND;
$dave['C']['PORTUGAL'] = PORTUGAL;
$dave['D']['DENMARK'] = DENMARK;
$dave['E']['SWITZERLAND'] = SWITZ;
$dave['F']['USA'] = USA;
$dave['G']['SOUTH KOREA'] = KOREA;
$dave['H']['JAPAN'] = JAPAN;
$dave['I']['AUSTRALIA'] = AUSTRALIA;
$dave['J']['QATAR'] = QATAR;
$dave['K']['MESSI'] = MESSI;
$dave['L']['RONALDO'] = RONALDO;
$dave['M']['LAUTARO'] = LAUTARO;
$dave['N']['RICHARLISON'] = RICHARLISON;
$dave['O']['GNABRY'] = GNABRY;
$dave['P']['DE BRUYNE'] = DEBRUYNE;
$dave['Q']['GAKPO'] = GAKPO;
$dave['R']['SON'] = SON;
$dave['S']['KAMADA'] = KAMADA;
$dave['T']['DAVID'] = DAVID;
define('DAVE', serialize($dave));

$aviva = array();
$aviva['name'] = 'Trophy Wife';
$aviva['A']['BRAZIL'] = BRAZIL;
$aviva['B']['SPAIN'] = SPAIN;
$aviva['C']['PORTUGAL'] = PORTUGAL;
$aviva['D']['URUGUAY'] = URUGUAY;
$aviva['E']['ECUADOR'] = ECUADOR;
$aviva['F']['USA'] = USA;
$aviva['G']['MOROCCO'] = MOROCCO;
$aviva['H']['CANADA'] = CANADA;
$aviva['I']['CAMEROON'] = CAMEROON;
$aviva['J']['COSTA RICA'] = COSTA;
$aviva['K']['MESSI'] = MESSI;
$aviva['L']['RONALDO'] = RONALDO;
$aviva['M']['VINICIUS JR'] = VINI;
$aviva['N']['LEWANDOWSKI'] = LEWANDOWSKI;
$aviva['O']['GRIEZMANN'] = GRIEZMANN;
$aviva['P']['DE BRUYNE'] = DEBRUYNE;
$aviva['Q']['VLAHOVIC'] = VLAHOVIC;
$aviva['R']['MODRIC'] = MODRIC;
$aviva['S']['KAMADA'] = KAMADA;
$aviva['T']['DAVIES'] = DAVIES;
define('AVIVA', serialize($aviva));

$christa = array();
$christa['name'] = 'Hit Mbappé One More Time';
$christa['A']['BRAZIL'] = BRAZIL;
$christa['B']['ENGLAND'] = ENGLAND;
$christa['C']['GERMANY'] = GERMANY;
$christa['D']['DENMARK'] = DENMARK;
$christa['E']['SWITZERLAND'] = SWITZ;
$christa['F']['SENEGAL'] = SENEGAL;
$christa['G']['WALES'] = WALES;
$christa['H']['GHANA'] = GHANA;
$christa['I']['CAMEROON'] = CAMEROON;
$christa['J']['QATAR'] = QATAR;
$christa['K']['MBAPPE'] = MBAPPE;
$christa['L']['BENZEMA'] = BENZEMA;
$christa['M']['VINICIUS JR'] = VINI;
$christa['N']['LEWANDOWSKI'] = LEWANDOWSKI;
$christa['O']['GRIEZMANN'] = GRIEZMANN;
$christa['P']['DE BRUYNE'] = DEBRUYNE;
$christa['Q']['VLAHOVIC'] = VLAHOVIC;
$christa['R']['MODRIC'] = MODRIC;
$christa['S']['JIMENEZ'] = JIMENEZ;
$christa['T']['DAVIES'] = DAVIES;
define('CHRISTA', serialize($christa));

$ryan = array();
$ryan['name'] = 'Coley\'s World Cup Squad I';
$ryan['A']['ARGENTINA'] = ARGENTINA;
$ryan['B']['ENGLAND'] = ENGLAND;
$ryan['C']['GERMANY'] = GERMANY;
$ryan['D']['DENMARK'] = DENMARK;
$ryan['E']['SWITZERLAND'] = SWITZ;
$ryan['F']['SENEGAL'] = SENEGAL;
$ryan['G']['SOUTH KOREA'] = KOREA;
$ryan['H']['CANADA'] = CANADA;
$ryan['I']['IRAN'] = IRAN;
$ryan['J']['TUNISIA'] = TUNISIA;
$ryan['K']['KANE'] = KANE;
$ryan['L']['NEYMAR'] = NEYMAR;
$ryan['M']['LAUTARO'] = LAUTARO;
$ryan['N']['RICHARLISON'] = RICHARLISON;
$ryan['O']['GNABRY'] = GNABRY;
$ryan['P']['FODEN'] = FODEN;
$ryan['Q']['GAKPO'] = GAKPO;
$ryan['R']['MODRIC'] = MODRIC;
$ryan['S']['HOJBJERG'] = HOJBJERG;
$ryan['T']['DAVID'] = DAVID;
define('RYAN', serialize($ryan));

$ryan2 = array();
$ryan2['name'] = 'Coley\'s World Cup Squad II';
$ryan2['A']['BRAZIL'] = BRAZIL;
$ryan2['B']['SPAIN'] = SPAIN;
$ryan2['C']['GERMANY'] = GERMANY;
$ryan2['D']['DENMARK'] = DENMARK;
$ryan2['E']['SWITZERLAND'] = SWITZ;
$ryan2['F']['SENEGAL'] = SENEGAL;
$ryan2['G']['WALES'] = WALES;
$ryan2['H']['GHANA'] = GHANA;
$ryan2['I']['CAMEROON'] = CAMEROON;
$ryan2['J']['TUNISIA'] = TUNISIA;
$ryan2['K']['MESSI'] = MESSI;
$ryan2['L']['NEYMAR'] = NEYMAR;
$ryan2['M']['DEPAY'] = DEPAY;
$ryan2['N']['RICHARLISON'] = RICHARLISON;
$ryan2['O']['GNABRY'] = GNABRY;
$ryan2['P']['ANSU FATI'] = FATI;
$ryan2['Q']['GAKPO'] = GAKPO;
$ryan2['R']['BERNARDO'] = BERNARDO;
$ryan2['S']['HOJBJERG'] = HOJBJERG;
$ryan2['T']['DAVIES'] = DAVIES;
define('RYAN2', serialize($ryan2));

/********************************/

$wc_teams = array();
$wc_teams[] = $mike;
$wc_teams[] = $mike2;
$wc_teams[] = $james;
$wc_teams[] = $james2;
$wc_teams[] = $seb;
$wc_teams[] = $dave;
$wc_teams[] = $aviva;
$wc_teams[] = $christa;
$wc_teams[] = $ryan;
$wc_teams[] = $ryan2;
define('WC_TEAMS', serialize($wc_teams));
